root: true
env:
    node: true
    es6: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
    project: "./tsconfig.json"
plugins:
    - "@typescript-eslint"
rules:
    no-eval: error
    no-debugger: error
    no-console: warn
    no-var: error
    no-unsafe-finally: error
    prefer-const: error
    prefer-rest-params: error
    prefer-spread: error
    no-duplicate-imports: off
    quotes: [error, single]
    semi: [error, always]
    max-len: [error, 120]
    "@typescript-eslint/no-unused-vars": warn
    "@typescript-eslint/prefer-interface": off
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-non-null-assertion": off
    "@typescript-eslint/no-empty-function": off
    "@typescript-eslint/explicit-module-boundary-types": off
ignorePatterns:
    - test/**/*.ts
    - dist/*
