trailingComma: es5
tabWidth: 4
semi: true
singleQuote: false
printWidth: 120
maxLineLength: 80
importOrder: ["^react", "^components/(.*)$", "^[./]", "^@/"]
importOrderSeparation: true
quoteProps: as-needed
jsxBracketSameLine: false
jsxSingleQuote: false
arrowParens: always
endOfLine: auto
