trailingComma: es5
singleAttributePerLine: true
tabWidth: 4
useTabs: true
semi: true
singleQuote: false
printWidth: 80
quoteProps: as-needed
jsxBracketSameLine: false
jsxSingleQuote: false
arrowParens: always
endOfLine: auto
importOrder: ["^components/(.*)$", "^[./]"]
importOrderSeparation: true
importOrderParserPlugins: ["decorators-legacy", "typescript"]
