version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
      # - ./data/postgres-data:/var/lib/postgresql/data
  storage:
    image: minio/minio:latest
    restart: always
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: miniominio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/minio-data:/data
    command: server --console-address ":9001" /data
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
        - MINIO_HOST=storage
        - MINIO_PUBLIC_URL=http://localhost:9000
        - MINIO_PORT=9000
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=miniominio
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - DATABASE_SYNCHRONIZE=true
        - API_PORT=3000
        - API_HOST=http://localhost/api/v0
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
      - storage
  pgadmin:
    image: dpage/pgadmin4:5.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: neighbook@admin.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgadmin_data: