version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - 3000:3000
volumes:
  db:
    driver: local