version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - docker.env
    ports:
      - '5433:5433'
    volumes:
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - docker.env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
volumes:
  db:
    driver: local