name: Auto deployment for api dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/api-nh-dev-server-AutoDeployTrigger-21d2a4b3-bc36-48db-a917-073d48ac215a.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: devengines.azurecr.io
          username: ${{ secrets.APINHDEVSERVER_REGISTRY_USERNAME }}
          password: ${{ secrets.APINHDEVSERVER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devengines.azurecr.io/api-nh-dev-server:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APINHDEVSERVER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n api-nh-dev-server -g rg-dev --server devengines.azurecr.io --username  ${{ secrets.APINHDEVSERVER_REGISTRY_USERNAME }} --password ${{ secrets.APINHDEVSERVER_REGISTRY_PASSWORD }}
            az containerapp update -n api-nh-dev-server -g rg-dev --image devengines.azurecr.io/api-nh-dev-server:${{ github.sha }}
